name: Publish

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: dawidd6/action-docker-publish-changed@master
        with:
          username: ${{github.event.repository.owner.login}}
          password: ${{secrets.PASS}}
          token: ${{secrets.GITHUB_TOKEN}}
          platforms: linux/amd64,linux/arm64,linux/arm
